on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Push to gh-pages
              run: |
                 git config user.name "github-actions[bot]"
                 git config user.email "github-actions[bot]@users.noreply.github.com"
                 git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/rkhue/sidebar-dad.git gh-pages

            - name: Deploy no GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ github.token }}
                  publish_dir: ./